# Generated by Django 6.1.1 on 2026-09-03 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del cliente (Formato: 12.345.678-9 o 12345678-K).', max_length=15, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(blank=True, default='Cliente Ocasional', help_text='Nombre del cliente habitual o identificación genérica.', max_length=120, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(blank=True, help_text='Opcional para cliente habitual.', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto o WhatsApp.', max_length=20, null=True, verbose_name='Teléfono')),
                ('cliente_habitual', models.BooleanField(default=False, help_text='Indica si el comprador aceptó registrarse como cliente frecuente.', verbose_name='¿Es Cliente Habitual?')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre', 'rut'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del producto (Obligatorio).', max_length=120, verbose_name='Nombre del Producto')),
                ('codigo', models.CharField(help_text='Identificador único del producto en el inventario.', max_length=50, unique=True, verbose_name='Código / SKU')),
                ('precio', models.PositiveIntegerField(help_text='Precio de venta en CLP. Debe ser un valor estrictamente mayor a 0.', verbose_name='Precio Unitario ($)')),
                ('stock', models.IntegerField(default=0, help_text='Unidades físicas disponibles. No puede ser un valor negativo.', verbose_name='Stock Disponible')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de incorporación al catálogo.', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Emisión')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Monto Total ($)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.cliente', verbose_name='Cliente Asociado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Subtotal Ítem ($)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.producto', verbose_name='Producto Vendido')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
